Repository nhn-on7/marketgg-auth, pull requests merged in 2022-08, with the labels that each got.

#49 구글 로그인
  src/main/java/com/nhnacademy/marketgg/auth/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/OAuth2Controller.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/request/GoogleProfileRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/GoogleProfile.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/OauthResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/jwt/CustomUser.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/auth/service/OAuth2Service.java
Labels: Feat

#51 정적 분석을 위한 코드 개선
  pom.xml
  src/main/java/com/nhnacademy/marketgg/auth/config/RestTemplateConfig.java
  src/main/java/com/nhnacademy/marketgg/auth/filter/JwtAuthenticationFilter.java
  src/test/java/com/nhnacademy/marketgg/auth/AuthApplicationTests.java
Labels: Docs, Refactor, Chore

#55 테스트 미흡한 부분 추가
  src/main/java/com/nhnacademy/marketgg/auth/adapter/GoogleAdapter.java
  src/main/java/com/nhnacademy/marketgg/auth/adapter/OauthAdapter.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/GoogleLoginController.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/GoogleProfile.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/MemberNameResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/jwt/TokenUtils.java
  src/main/java/com/nhnacademy/marketgg/auth/service/AuthInfoService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/Oauth2Service.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthInfoService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/GoogleLoginService.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/AuthInfoControllerTest.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/GoogleLoginControllerTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthInfoServiceTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/GoogleLoginServiceTest.java
Labels: Test

#57 Hotfix: Google Login Fix
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/GoogleProfile.java
Labels: Fix

#60 예외 메세지 다국어 처리
  pom.xml
  src/main/java/com/nhnacademy/marketgg/auth/config/MessageConfiguration.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/advice/AuthControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/advice/AuthInfoControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/advice/ExceptionMessageCode.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/advice/GlobalExceptionAdvice.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/AuthException.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/AuthWithDrawOverlapException.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/AuthWithdrawOverlapException.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/ConflictException.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/EmailOverlapException.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/InvalidLoginRequestException.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/LoginFailException.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/OAuthRequestFailException.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/SecureManagerException.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/UnAuthorizationException.java
  src/main/resources/application.yml
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
Labels: Feat

#64 Hotfix: 로그아웃 오류 수정
  src/main/java/com/nhnacademy/marketgg/auth/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/MemberResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/filter/JwtAuthenticationFilter.java
Labels: Fix

#74 회원가입 이메일 인증 추가
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/SignUpResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpService.java
  src/test/java/com/nhnacademy/marketgg/auth/AuthApplicationTests.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/AuthControllerTest.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/LoginTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpServiceTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultUserDetailsServiceTest.java
Labels: Feat, Refactor, Test

#72 탈퇴 회원 관리
  src/main/java/com/nhnacademy/marketgg/auth/aop/advice/AuthControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/auth/aop/advice/ExceptionMessageCode.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/GoogleLoginController.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/SignUpController.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/request/signup/EmailRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/request/signup/EmailUseRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/request/signup/SignUpRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/login/oauth/OauthLoginResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/login/oauth/OauthProfile.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/login/oauth/TokenResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/login/oauth/google/GoogleProfile.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/signup/EmailResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/signup/ExistEmailResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/signup/SignUpResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/signup/UseEmailResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Auth.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/WithdrawMemberException.java
  src/main/java/com/nhnacademy/marketgg/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/nhnacademy/marketgg/auth/jwt/TokenUtils.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/auth/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/auth/AuthRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/auth/AuthRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/authrole/AuthRoleRepository.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/role/RoleRepository.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/role/RoleRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/role/RoleRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/auth/service/AuthInfoService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/AuthService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/Oauth2Service.java
  src/main/java/com/nhnacademy/marketgg/auth/service/SignUpService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthInfoService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultUserDetailsService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/GoogleLoginService.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
  src/test/java/com/nhnacademy/marketgg/auth/controller/AuthControllerTest.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/GoogleLoginControllerTest.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/LoginTest.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/SignUpControllerTest.java
  src/test/java/com/nhnacademy/marketgg/auth/repository/AuthRepositoryTest.java
  src/test/java/com/nhnacademy/marketgg/auth/repository/RoleRepositoryTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthInfoServiceTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthServiceTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpServiceTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultUserDetailsServiceTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/GoogleLoginServiceTest.java
Labels: Feat, Refactor

#79 Refactor: 토큰 갱신 오류 수정
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
  src/main/java/com/nhnacademy/marketgg/auth/jwt/TokenUtils.java
Labels: Fix

#81 Chore: 배포 수정
  .github/workflows/main.yml
  .github/workflows/maven.yml
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
Labels: Chore

#87 회원 수정, 삭제 Final
  lombok.config
  src/main/java/com/nhnacademy/marketgg/auth/aop/TokenAspect.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/request/AuthWithDrawRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/request/MemberUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/UuidTokenResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Auth.java
  src/main/java/com/nhnacademy/marketgg/auth/service/AuthInfoService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthInfoService.java
Labels: Feat, Refactor
