Repository nhn-on7/marketgg-auth, pull requests merged in 2022-07, with the labels that each got.

#3 Feat: 인증서버 엔티티 매핑 #2
  pom.xml
  src/main/java/com/nhnacademy/marketgg/auth/entity/Auth.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/AuthRoles.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Role.java
  src/main/resources/application.yml
Labels: Feat

#8 Feature: 회원가입 아이디, 이메일 중복 체크 기능추가
  .github/ISSUE_TEMPLATE/feature.md
  src/main/java/com/nhnacademy/marketgg/auth/config/RedisConfig.java
  src/main/java/com/nhnacademy/marketgg/auth/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/EmailRequestDto.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/SignupRequestDto.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/UsernameRequestDto.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Auth.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/AuthRoles.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Provider.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Role.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Roles.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Token.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/auth/service/AuthService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/DefaultAuthService.java
  src/main/resources/application.yml
  src/test/java/com/nhnacademy/marketgg/auth/controller/AuthControllerTest.java
  src/test/java/com/nhnacademy/marketgg/auth/repository/AuthRepositoryTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/DefaultAuthServiceTest.java
Labels: Feat

#7 Feature/login
  pom.xml
  src/main/java/com/nhnacademy/marketgg/auth/config/RedisConfig.java
  src/main/java/com/nhnacademy/marketgg/auth/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/request/LoginRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/TokenResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Auth.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/AuthRole.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Provider.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Role.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Roles.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Token.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/AuthNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/LoginFailException.java
  src/main/java/com/nhnacademy/marketgg/auth/jwt/CustomUser.java
  src/main/java/com/nhnacademy/marketgg/auth/jwt/RefreshToken.java
  src/main/java/com/nhnacademy/marketgg/auth/jwt/TokenGenerator.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/RoleRepository.java
  src/main/java/com/nhnacademy/marketgg/auth/service/AuthService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/DefaultAuthService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultUserDetailsService.java
  src/main/resources/application.yml
  src/test/java/com/nhnacademy/marketgg/auth/controller/AuthControllerTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/DefaultAuthServiceTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthServiceTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultUserDetailsServiceTest.java
Labels: Feat

#11 Feat: 구글 로그인 진행 #10
  src/main/java/com/nhnacademy/marketgg/auth/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/auth/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/OAuth2Controller.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/request/SignupRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/GoogleProfile.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/TokenResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/OAuthRequestFailException.java
  src/main/java/com/nhnacademy/marketgg/auth/oauth2/OAuthToken.java
  src/main/java/com/nhnacademy/marketgg/auth/oauth2/TokenRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/service/AuthService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/OAuth2Service.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthService.java
  src/main/resources/application.yml
  src/test/java/com/nhnacademy/marketgg/auth/controller/AuthControllerTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthServiceTest.java
Labels: Feat

#12 리프레시 토큰 발급
  src/main/java/com/nhnacademy/marketgg/auth/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Auth.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/AuthRole.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Role.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/IllegalTokenException.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/InvalidLoginRequestException.java
  src/main/java/com/nhnacademy/marketgg/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/nhnacademy/marketgg/auth/jwt/RefreshToken.java
  src/main/java/com/nhnacademy/marketgg/auth/jwt/TokenGenerator.java
  src/main/java/com/nhnacademy/marketgg/auth/service/AuthService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultUserDetailsService.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/AuthControllerTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthServiceTest.java
Labels: Feat

#23 오탈자 수정
  src/main/java/com/nhnacademy/marketgg/auth/config/RedisConfig.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/TokenResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/RoleRepositoryCustom.java
Labels: Feat

#25 Refactor: 회원가입 추천인 로직 추가
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/request/SignUpRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/SignUpResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/UseEmailResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthService.java
Labels: Refactor

#27 로그인 / 로그아웃 테스트
  pom.xml
  src/main/java/com/nhnacademy/marketgg/auth/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/auth/constant/Provider.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/OAuth2Controller.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Auth.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/AuthRole.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Role.java
  src/main/java/com/nhnacademy/marketgg/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/nhnacademy/marketgg/auth/jwt/CustomUser.java
  src/main/java/com/nhnacademy/marketgg/auth/jwt/RefreshToken.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/RoleRepository.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/RoleRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/RoleRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/auth/service/AuthService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultUserDetailsService.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/AuthControllerTest.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/LoginTest.java
  src/test/java/com/nhnacademy/marketgg/auth/repository/RoleRepositoryTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthServiceTest.java
  src/test/resources/application.yml
Labels: Test

#30 Chore/package
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/SignUpController.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/AuthNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/auth/service/AuthInfoService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/AuthService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/SignUpService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthInfoService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpService.java
  src/main/java/com/nhnacademy/marketgg/auth/util/RedisUtils.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/SignUpControllerTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpServiceTest.java
Labels: Chore

#32 Fix: 회원탈퇴 로직 추가를 위해 Entity 필드 수정 및 Comment 반영
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/request/AuthUpdateRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/request/AuthWithDrawRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/request/EmailRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/AuthUpdateResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Auth.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/AuthNotFoundException.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/AuthWithDrawOverlapException.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/UnAuthorizationException.java
  src/main/java/com/nhnacademy/marketgg/auth/jwt/TokenUtils.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/auth/service/AuthInfoService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/AuthService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthInfoService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthService.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/LoginTest.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/SignUpControllerTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpServiceTest.java
Labels: Refactor

#36 AOP 를 이용하여 토큰 검증 후 전달
  src/main/java/com/nhnacademy/marketgg/auth/annotation/Token.java
  src/main/java/com/nhnacademy/marketgg/auth/aspect/TokenAspect.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/ExistEmailResponse.java
Labels: Feat

#37 컨트롤러 클래스 기능 분리
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/SignUpController.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/TokenController.java
  src/main/java/com/nhnacademy/marketgg/auth/exception/IllegalTokenException.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpService.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/AuthControllerTest.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/LoginTest.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/SignUpControllerTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthServiceTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpServiceTest.java
Labels: Refactor

#39 Refactor: Test code 수정
  src/main/java/com/nhnacademy/marketgg/auth/AuthApplication.java
  src/main/java/com/nhnacademy/marketgg/auth/aspect/TokenAspect.java
  src/main/java/com/nhnacademy/marketgg/auth/jwt/TokenUtils.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/AuthControllerTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthServiceTest.java
Labels: Refactor

#41 Style 가이드, 회원탈퇴 로직 변경
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/request/EmailRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/request/EmailUseRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/UseEmailResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/AuthRepository.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/AuthRoleRepository.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/RoleRepository.java
  src/main/java/com/nhnacademy/marketgg/auth/service/SignUpService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthInfoService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpService.java
Labels: Refactor

#46 인증서 템플릿에 적용
  .github/workflows/maven.yml
  maven.yml
  pom.xml
  src/main/java/com/nhnacademy/marketgg/auth/aspect/TokenAspect.java
  src/main/java/com/nhnacademy/marketgg/auth/config/RedisConfig.java
  src/main/java/com/nhnacademy/marketgg/auth/config/RestTemplateConfig.java
  src/main/java/com/nhnacademy/marketgg/auth/config/WebConfig.java
  src/main/java/com/nhnacademy/marketgg/auth/config/WebSecurityConfig.java
  src/main/java/com/nhnacademy/marketgg/auth/jwt/TokenUtils.java
  src/main/java/com/nhnacademy/marketgg/auth/service/OAuth2Service.java
  src/main/java/com/nhnacademy/marketgg/auth/util/MailUtils.java
  src/main/resources/application.yml
  src/main/resources/clientCertificate.p12
  src/test/java/com/nhnacademy/marketgg/auth/controller/LoginTest.java
  src/test/resources/application.yml
Labels: Feat, Fix, Docs, Style

#48 정적 분석 결과 개선
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Auth.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/AuthControllerTest.java
Labels: Feat, Docs, Style, Refactor
