Repository nhn-on7/marketgg-auth, pull requests merged in 2022-09, with the labels that each got.

#88 Fix: 추천인 uuid 반환 수정
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpService.java
Labels: Fix

#86 관리자 회원 목록 조회 API 개발
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/Payload.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/request/DefaultPageRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/AdminMemberResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/common/PageEntity.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/auth/AuthRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/auth/AuthRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/authrole/AuthRoleRepository.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/role/RoleRepositoryCustom.java
  src/main/java/com/nhnacademy/marketgg/auth/repository/role/RoleRepositoryImpl.java
  src/main/java/com/nhnacademy/marketgg/auth/service/AuthInfoService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthInfoService.java
  src/test/java/com/nhnacademy/marketgg/auth/controller/AuthInfoControllerTest.java
  src/test/java/com/nhnacademy/marketgg/auth/repository/AuthRepositoryTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthInfoServiceTest.java
Labels: Feat

#84 Docs: 인증 관련 Swagger 적용
  pom.xml
  src/main/java/com/nhnacademy/marketgg/auth/config/SwaggerConfig.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/GoogleLoginController.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/request/LoginRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/request/MemberInfoRequest.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/MemberNameResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/MemberResponse.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/common/AuthResult.java
  src/main/java/com/nhnacademy/marketgg/auth/dto/response/login/oauth/google/GoogleProfile.java
  src/main/java/springfox/documentation/spring/web/plugins/WebMvcRequestHandlerProvider.java
Labels: Docs

#89 Refactor: 탈퇴 회원 관리
  src/main/java/com/nhnacademy/marketgg/auth/aop/advice/AuthControllerAdvice.java
  src/main/java/com/nhnacademy/marketgg/auth/aop/advice/ExceptionMessageCode.java
  src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
  src/main/java/com/nhnacademy/marketgg/auth/entity/Auth.java
  src/main/java/com/nhnacademy/marketgg/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/nhnacademy/marketgg/auth/jwt/CustomUser.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultUserDetailsService.java
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/GoogleLoginService.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthServiceTest.java
  src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultUserDetailsServiceTest.java
Labels: Feat

#90 Hotfix/refresh
  .github/workflows/main.yml
  .github/workflows/maven.yml
  src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthService.java
Labels: Fix
